---
abstract: 'RPC::ExtDirect gateway for Plack'
author:
  - 'Alex Tokarev <tokarev@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
  Test::More: 0.82
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.84, CPAN::Meta::Converter version 2.132661'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-ExtDirect
no_index:
  directory:
    - t
    - inc
requires:
  Plack: 1.0
  RPC::ExtDirect: 3.02
  perl: 5.008
resources:
  bugtracker: https://github.com/nohuhu/Plack-Middleware-ExtDirect/issues
  repository: https://github.com/nohuhu/Plack-Middleware-ExtDirect
version: 3.01
